apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: github-jenkins-artifactory-dotnet-14x-gitops
  description: This is GitOps manifest for github-jenkins-artifactory-dotnet-14x   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: github-jenkins-artifactory-dotnet-14x
    backstage.io/kubernetes-id: github-jenkins-artifactory-dotnet-14x 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: github-jenkins-artifactory-dotnet-14x-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:github-jenkins-artifactory-dotnet-14x
