apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: github-jenkins-artifactory-dotnet-14x
  janus-idp.io/tekton: github-jenkins-artifactory-dotnet-14x
  backstage.io/kubernetes-id: github-jenkins-artifactory-dotnet-14x
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: github-jenkins-artifactory-dotnet-14x
resources:
- deployment.yaml
- route.yaml
- service.yaml
