apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: github-jenkins-artifactory-dotnet-14x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-jenkins-artifactory-dotnet-14x 
  name: github-jenkins-artifactory-dotnet-14x
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: github-jenkins-artifactory-dotnet-14x
    weight: 100 
