apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-jenkins-artifactory-dotnet-14x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-jenkins-artifactory-dotnet-14x 
  name: github-jenkins-artifactory-dotnet-14x
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-jenkins-artifactory-dotnet-14x 
